
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.251:3306/shirotest?characterEncoding=utf-8&useSSl=false&serverTimezone=GMT%2B8
    # hikari 方式连接
#    hikari:
#      maximum-pool-size: 10 # 最大连接池
#      minimum-idle: 0 # 允许最小空闲数
#      idle-timeout: 180000 # 超时(毫秒)
#      connection-test-query: SELECT 1

    # durid 方式连接
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    druid:
      # 多数据源
      db1:
        jdbc-url: jdbc:mysql://192.168.1.251:3306/shirotest?characterEncoding=utf-8&useSSl=false&serverTimezone=GMT%2B8
        username: root
        password: root
      db2:
        jdbc-url: jdbc:mysql://192.168.1.251:3306/shirotest?characterEncoding=utf-8&useSSl=false&serverTimezone=GMT%2B8
        username: root
        password: root
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: SELECT 1
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: false  # 是否缓存 preparedStatement 即 PSCache mysql下建议关闭
#      maxPoolPreparedStatementPerConnectionSize: 20  # PSCache 缓存大小
#      maxOpenPreparedStatements: 20  # 同上
      # 通过 connectionProperties 打开慢日志记录 配置加密
      # ;config.decrypt=true
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123

  rabbitmq:
    host: 192.168.1.251
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    # 开启发送确认
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual  # 手动 ack
        retry:
          enabled: true   # 消费者重试

      simple:
        acknowledge-mode: manual  # 手动 ack
        retry:
          enabled: true
        concurrency: 10  # 消费者最小数量
        max-concurrency: 20 # 消费者最大数量
        prefetch: 5  # 每个消费者未处理消息数
        auto-startup: true  # 启动时自动启动容器
        default-requeue-rejected: true  # 投递失败后重新排队

    template:
      reply-timeout: 10000  # 超时
      retry:
        enabled: true
        initial-interval: 1000 # 第一次与第二次消息发布时间间隔 1000ms
        max-attempts: 3  # 重试次数
        max-interval: 10000 # 重试间隔
        multiplier: 1.0  # 上次尝试的时间间隔 乘上 基数
  redis:
    shiro:
      host: 192.168.1.251:6379
      password: ryrbz
      timeout: 5000
      database: 5

  thymeleaf:
    cache: false

logging:
  level:
    com.amoyiki.springtest.mapper: DEBUG
# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # 配置Mapper.xml文件所在路径
  type-aliases-package: com.amoyiki.springtest.entry   # 配置别名