
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.200:3306/springtest?characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true


  redis:
    shiro:
      host: 192.168.1.200:6379
      password: root
      timeout: 5000
      database: 5