spring:
  # 默认选择开发环境
  profiles:
    active:
      - dev

  # 公共配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml # ehcache 配置文件


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
